spring.application.name=consultoriomedico

server.port=3000
# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://us-east-1.44e7a8b3-debc-4971-a789-84242240a575.aws.yugabyte.cloud:5433/yugabyte
spring.datasource.username=admin
spring.datasource.password=MnBUSd7-Zxuwc2VSiaR09JgFD28wk3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    