spring.application.name=consultoriomedico

server.port=8080
# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://us-east-1.007b0ec3-802c-473e-9072-a77f139218ab.aws.yugabyte.cloud:5433/yugabyte
spring.datasource.username=admin
spring.datasource.password=8o59q9nyQV5i3JKkrfAkw_7CdOAhar
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/documentacion/swagger-ui.html
springdoc.paths-to-match=/api/**    

# Configuración de email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sistemamedico2025@gmail.com
spring.mail.password=lymh hsjm rbnb fxih

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connection-timeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.write-timeout=5000